### PR TITLE
pstore: Reserve memory via DT for ramoops contents

### PR DESCRIPTION
**Pull request by Noob-214**

### CODE REVIEW

**Comment by zqm64** [comment]
@Noob-214 The commit message is OK at this time

**Comment by zqm64** [comment]
@Noob-214 But I plan to make overlayed dts, so I won't merge this

**Comment by Noob-214** [comment]
okay

**Comment by zqm64** [comment]
@Noob-214 Wait, you should use "dts: qcom:" as prefix, not "pstore:"

**Comment by Noob-214** [comment]
sorry I forgets

**Pull request closed without merging**
